version: '3.8'

services:
  app:
    image: my-laravel-app  # اسم الصورة الخاصة بك
    build:
      context: .  # المسار الذي يحتوي على Dockerfile
    ports:
      - "80:80"  # يربط المنفذ 80 على المضيف بالمنفذ 80 على الحاوية
    volumes:
      - .:/var/www/html  # ربط المجلد المحلي بمجلد داخل الحاوية
    environment:
      - APP_ENV=local  # تأكد من إضافة أي متغيرات بيئية تحتاجها

